config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'home/index'
  
  resources :jobs do
  	resources :applications, except: [:index]
  end

  root 'home#index'

  

end

app/models/application.rb
class Application < ApplicationRecord

	belongs_to :user
	belongs_to :job
	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
	
	belongs_to :user
	has_many :applications, dependent: :destroy
	 
	validates :title, :description, presence: true

end

app/models/user.rb
class User < ApplicationRecord

  has_many :jobs
  has_many :applications, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
	before_action :find_application, only: [:show, :edit, :update, :destroy]
	before_action :find_job
	before_action :authenticate_user!

	def show
		if current_user.admin
			@application.seen = true
			@application.save
		end
	end

	def new
		@application = Application.new
	end

	def edit

	end

	def create
		@application = Application.new(application_params)
		@application.user_id = current_user.id
		@application.job_id = @job.id

		if @application.save
			redirect_to @job
		else
			render 'new'
		end
	end

	def update
		@application.update(application_params)
	end

	def destroy
		@application.destroy
		redirect_to jobs_path
	end

	private
		def find_application
			@application = Application.find(params[:id])
		end

		def find_job
			@job = Job.find(params[:job_id])
		end

		def application_params
			params.require(:application).permit(:extra_information)
		end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
  
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	before_action :find_job, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:show, :index]

	def index
    	@job = Job.all
    	@application = Application.all
  	end

	def show 
		@application = Application.where(job_id: @job.id)
	end

	def new
		@job = Job.new
	end

	def edit
	end

	def create
		@job = Job.new(job_params)
		@job.user = current_user
		if @job.save
			redirect_to @job
		else
			render 'new'
		end
	end

	def update
		if @job.update(job_params)
			redirect_to @job
		else
			render 'edit'
		end
	end	

	def destroy
		@job.destroy
		redirect_to jobs_path
	end

private 

	def job_params
		params.require(:job).permit(:title, :description)
	end

	def find_job
		@job = Job.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/job_posts_helper.rb
module JobPostsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/applications/_form.html.erb
<%= form_for([@job, @application]) do |f| %>
  <% if @application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@application.errors.count, "error") %> prohibited this application from being submitted:</h2>

      <ul>
      <% @application.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :extra_information %><br>
    <%= f.text_area :extra_information, cols: "30", rows: "10" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/applications/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Job Home</title>
<style>
/* Style the body */
body {
  font-family: Arial;
  margin: 0;
}

/* Header/Logo Title */
.header {
  padding: 15px;
  text-align: center;
  background: #6bc3b0;
  color: white;
  font-size: 30px;
}

.container { 
  padding: 40px;    
    background-color: white;  
    padding-left: 30%;
 } 

.form {   
    border: 3px solid #f1f1f1;  
 }  

.button {   
       background-color: white;   
       width: 100%;   
       padding: 15px;   
       margin: 10px 0px;   
       border: none;   
       cursor: pointer;
       padding-left: 48%;   
} 


</style>
</head>
<body>

<div class="header">
  <h1>ZenHR</h1>
</div>


<h1>New Job Application</h1>

<div class="form">
<%= render 'form' %>
</div>

<div class='action'>
<%= link_to 'Back', job_path(@job) %>
</div>

</body>
</html>

app/views/applications/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Application</title>
<style>
/* Style the body */
body {
  font-family: Arial;
  margin: 0;
}

/* Header/Logo Title */
.header {
  padding: 15px;
  text-align: center;
  background: #6bc3b0;
  color: white;
  font-size: 30px;
}

.container { 
  padding: 40px;    
    background-color: white;  
    padding-left: 30%;
 } 

.form {   
    border: 3px solid #f1f1f1;  
 }  

.button {   
       background-color: white;   
       width: 100%;   
       padding: 15px;   
       margin: 10px 0px;   
       border: none;   
       cursor: pointer;
       padding-left: 48%;   
} 


</style>
</head>
<body>

<div class="header">
  <h1>ZenHR</h1>
</div>

<div class='applicantOutput'>
<p>
  <strong>Applicant Name:</strong>
  <%= @application.user.email.split("@")[0] %>
</p>
</div>
 
<div class='jobTitleOutput'>
<p>
  <strong>Job Title:</strong>
  <%= @application.job.title %>
</p>
</div>

<div class='action'>
<%= link_to 'Back', jobs_path %>
</div>

</body>
</html>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>

<style>
/* Style the body */
body {
  font-family: Arial;
  margin: 0;
}

/* Header/Logo Title */
.header {
  padding: 15px;
  text-align: center;
  background: #6bc3b0;
  color: white;
  font-size: 30px;
}

.container { 
	padding: 40px;    
    background-color: white;  
    padding-left: 30%;
 } 

.form {   
    border: 3px solid #f1f1f1;  
 }  

.button {   
       background-color: white;   
       width: 100%;   
       padding: 15px;   
       margin: 10px 0px;   
       border: none;   
       cursor: pointer;
       padding-left: 48%;   
} 


</style>
</head>
<body>

<div class="header">
  <h1>ZenHR</h1>
</div>

<div class='action' style=" padding-top: 10%">
<% if current_user %>
  <%= link_to 'Job Posts', controller: 'jobs' %>
  <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to 'Sign in', new_user_session_path %>
  <%= link_to 'Sign up', new_user_registration_path %>
<% end %>
</div>


</body>
</html>

app/views/jobs/_form.html.erb
<%= form_with model: @job, local: true do |form| %>
 
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@job.errors.count, "error") %> prohibited
        this job post from being saved:
      </h2>
      <ul>
        <% @job.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
<div class="title">
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
</div>
 
<div class='description'> 
  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description, cols: "30", rows: "10" %>
  </p>
</div>

  <p>
    <%= form.submit "Submit"%>
  </p>
<% end %>

app/views/jobs/edit.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Edit Job</title>
<style>
/* Style the body */
body {
  font-family: Arial;
  margin: 0;
}

/* Header/Logo Title */
.header {
  padding: 15px;
  text-align: center;
  background: #6bc3b0;
  color: white;
  font-size: 30px;
}

.container { 
  padding: 40px;    
    background-color: white;  
    padding-left: 30%;
 } 

.form {   
    border: 3px solid #f1f1f1;  
 }  

.button {   
       background-color: white;   
       width: 100%;   
       padding: 15px;   
       margin: 10px 0px;   
       border: none;   
       cursor: pointer;
       padding-left: 48%;   
} 


</style>
</head>
<body>

<div class="header">
  <h1>ZenHR</h1>
</div>

<h1>Edit Job Post</h1>

<div class='form'>
<%= render 'form' %>
</div>

<div class='action'>
<%= link_to 'Back', jobs_path %>
</div>

</body>
</html>

app/views/jobs/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Job Home</title>
<style>
/* Style the body */
body {
  font-family: Arial;
  margin: 0;
}

/* Header/Logo Title */
.header {
  padding: 15px;
  text-align: center;
  background: #6bc3b0;
  color: white;
  font-size: 30px;
}

.container { 
  padding: 40px;    
    background-color: white;  
    padding-left: 30%;
 } 

.form {   
    border: 3px solid #f1f1f1;  
 }  

.button {   
       background-color: white;   
       width: 100%;   
       padding: 15px;   
       margin: 10px 0px;   
       border: none;   
       cursor: pointer;
       padding-left: 48%;   
} 

table, th, td {
  border: 1px solid #ddd;
}

table {
  border-collapse: collapse;
}

th, td {
  padding: 15px;
}


</style>
</head>
<body>

<div class="header">
  <h1>ZenHR</h1>
</div>

<h2>Listing Job Posts</h2>
 
<% if current_user && current_user.admin %>
  <div class='action'>
    <%= link_to 'New job post', new_job_path %>
  </div>
<%end%>

</br>

<h3>Job Posts:</h3>

<% if @job.blank? %>
<h4>No jobs found</h4>
<% else %>

<table align="center">
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Action</th>
  </tr>
 
  <% @job.each do |job| %>
    <tr>
      <td><%= job.title %></td>
      <td><%= job.description %></td>
      <td><%= link_to 'Show', job_path(job) %>
      <% if current_user && current_user.admin %>
      <%= link_to 'edit', edit_job_path(job) %>
      <%= link_to 'delete', job_path(job), 
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
      <%end%>
    </tr>
  <% end %>
</table>

<% end %>

</br>

<% if current_user && current_user.admin %>
  <% if @application.blank? %>
    <h3> No applicants application submitted yet</h3>
  <% else %>

    <h3>Applications submitted:</h3>

    <table align="center">
      <tr>
        <th>User ID</th>
        <th>Job ID</th>
        <th>Extra information</th>
        <th>Action</th>
      </tr>
 
      <% @application.each do |application| %>
      <tr>
          <td><%= application.user.email.split("@")[0] %></td>
          <td><%= application.job.title %></td>
          <td><%= application.extra_information %></td>
          <td><%= link_to 'View Application', job_application_path(application.job,application) %></td>
      </tr>
      <% end %>
    </table>
  <% end %>
<%end%>

</br>

<div class='action'>
  <%= link_to 'Back', controller: 'home' %>
  <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
</div>


</body>
</html>

app/views/jobs/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>New Job</title>
<style>
/* Style the body */
body {
  font-family: Arial;
  margin: 0;
}

/* Header/Logo Title */
.header {
  padding: 15px;
  text-align: center;
  background: #6bc3b0;
  color: white;
  font-size: 30px;
}

.container { 
  padding: 40px;    
    background-color: white;  
    padding-left: 30%;
 } 

.form {   
    border: 3px solid #f1f1f1;  
 }  

.button {   
       background-color: white;   
       width: 100%;   
       padding: 15px;   
       margin: 10px 0px;   
       border: none;   
       cursor: pointer;
       padding-left: 48%;   
} 


</style>
</head>
<body>

<div class="header">
  <h1>ZenHR</h1>
</div>

<h1>New Job Post</h1>

<div class="form">
<%= render 'form' %>
</div>

<div class='action'>
<%= link_to 'Back', jobs_path %>
</div>

</body>
</html>

app/views/jobs/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Job Posts</title>
<style>
/* Style the body */
body {
  font-family: Arial;
  margin: 0;
}

/* Header/Logo Title */
.header {
  padding: 15px;
  text-align: center;
  background: #6bc3b0;
  color: white;
  font-size: 30px;
}

.container { 
  padding: 40px;    
    background-color: white;  
    padding-left: 30%;
 } 

.form {   
    border: 3px solid #f1f1f1;  
 }  

.button {   
       background-color: white;   
       width: 100%;   
       padding: 15px;   
       margin: 10px 0px;   
       border: none;   
       cursor: pointer;
       padding-left: 48%;   
} 


</style>
</head>
<body>

<div class="header">
  <h1>ZenHR</h1>
</div>

<h2>Job Post</h2>

<div class='titleOutput'>
<p>
  <strong>Title:</strong>
  <%= @job.title %>
</p>
</div>
 
<div class='descriptionOutput'>
<p >
  <strong>Description:</strong>
  <%= @job.description %>
</p>
</div>

</br>

<% if current_user && !current_user.admin %>
	<% if @application.blank? %>
		<h3> No application submitted to this job post </h3>
    <div class='action'>
		  <%= link_to 'Apply', new_job_application_path(@job)%>
    </div>
	<% else %>
		<h2>Application Submitted:</h2>
			<% @application.each do | application |%>
				<p> <b>Job title:</b> <%= application.job.title %></p>
				<p> <b>Application extra information:</b> <%= application.extra_information %></p>
				<% if application.seen == true %>
				<p><b>Application status:</b> Seen</p>
				<% else %>
				<p><b>Application status:</b> Not seen</p>
				<% end %>
			<% end %>
	<%end%>	
<%end%>

<div class='action'>
<%= link_to 'Back', jobs_path %>
<% if current_user && current_user.admin %>
<%= link_to 'Edit', edit_job_path(@job) %> 
<% end %>

</div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZenAssignment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <p class="notice" style="text-align:center"><%= notice %></p>
    <p class="alert" style="text-align:center"><%= alert %></p>
  </body>
</html>